version: "3.9"
    
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Password1
      MYSQL_DATABASE: feedback_db
      MYSQL_USER: andrei
      MYSQL_PASSWORD: Password1
    ports:
      - '3307:3306'

  backend:
      container_name: backend
      build:
        context: ./FeedbackForm
        dockerfile: Dockerfile
      ports:
        - '5000:80'

  angular-frontend:
    container_name: frontend-portal
    build:
      context: ./ClientApp
      dockerfile: Dockerfile
    ports:
      - '80:80'
    environment:
      - NODE_ENV=production
